import Link from "next/link";
import Image from "next/image";
import { notFound } from "next/navigation";
import { ChevronLeft } from "lucide-react";
import { AppShell } from "@/components/layout/app-shell";
import { OrderActions } from "@/components/service-orders/order-actions";
import { getServiceOrder } from "@/lib/data/service-orders";
import { formatCurrencyBRL,formatDateBR,formatMileage,formatWhatsapp } from "@/lib/utils/formatters";
import type { ServiceOrderItem } from "@/types/service-order";

export default async function OrderPage({params}:{params:Promise<{id:string}>}){
  const order=await getServiceOrder((await params).id);if(!order)notFound();
  const items=[{label:"Cliente",value:order.customerName},{label:"WhatsApp",value:formatWhatsapp(order.whatsapp)},{label:"Motocicleta",value:order.model},{label:"Ano",value:String(order.year)},{label:"Placa",value:order.plate},{label:"Quilometragem",value:formatMileage(order.mileage)},{label:"Data",value:formatDateBR(order.date)}];
  return <AppShell><div className="no-print mb-5"><Link href="/historico" className="inline-flex items-center gap-2 text-sm font-bold text-[#999] hover:text-white"><ChevronLeft size={17}/>Voltar ao histórico</Link></div><article className="print-sheet overflow-hidden rounded-xl border border-[#303030] bg-[#131313]"><header className="flex flex-col justify-between gap-5 border-b border-[#2a2a2a] bg-[#0e0e0e] p-6 sm:flex-row sm:items-center sm:p-8"><div><p className="text-xs font-black uppercase tracking-[.22em] text-[#e60012]">Ordem de Serviço</p><h1 className="mt-2 text-3xl font-black text-white">{order.number}</h1><p className="mt-2 text-sm text-[#888]">Atendimento registrado em {formatDateBR(order.date)}</p></div><div className="relative h-20 w-48"><Image src="/images/nuna-moto-logo.png" alt="NUNA MOTO" fill className="object-contain object-right"/></div></header><div className="p-6 sm:p-8"><div className="grid gap-px overflow-hidden rounded-lg border border-[#2b2b2b] bg-[#2b2b2b] sm:grid-cols-2 lg:grid-cols-4">{items.map(item=><div key={item.label} className="bg-[#171717] p-4"><span className="text-xs font-bold uppercase tracking-wider text-[#777]">{item.label}</span><p className={`mt-2 font-semibold text-white ${item.label==="Placa"?"font-mono tracking-wider":""}`}>{item.value}</p></div>)}</div><div className="mt-7 grid gap-6 lg:grid-cols-2"><InfoList title="Serviços realizados" items={order.servicesPerformed}/><InfoList title="Peças substituídas" items={order.replacedParts} empty="Nenhuma peça substituída"/></div>{order.notes&&<section className="mt-6 rounded-lg border border-[#2b2b2b] bg-[#171717] p-5"><h2 className="text-sm font-black uppercase tracking-wider text-[#888]">Observações</h2><p className="mt-3 leading-7 text-[#ddd]">{order.notes}</p></section>}<div className="mt-7 flex flex-col justify-between gap-5 border-t border-[#2c2c2c] pt-7 sm:flex-row sm:items-end"><OrderActions id={order.id} number={order.number}/><div className="text-left sm:text-right"><p className="text-sm font-bold uppercase tracking-wider text-[#888]">Valor total</p><strong className="mt-1 block text-3xl font-black text-white">{formatCurrencyBRL(order.totalCents)}</strong></div></div></div></article></AppShell>;
}

function InfoList({title,items,empty}:{title:string;items:ServiceOrderItem[];empty?:string}){return <section><h2 className="mb-3 text-sm font-black uppercase tracking-wider text-[#888]">{title}</h2><div className="min-h-32 rounded-lg border border-[#2b2b2b] bg-[#171717] p-5">{items.length?<ul className="space-y-3">{items.map((item,index)=><li key={`${item.description}-${index}`} className="flex items-start justify-between gap-4 text-[#eee]"><span className="flex gap-3"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-[#e60012]"/>{item.description}</span>{item.valueCents!==undefined&&<strong className="shrink-0 text-white">{formatCurrencyBRL(item.valueCents)}</strong>}</li>)}</ul>:<p className="text-sm text-[#777]">{empty}</p>}</div></section>}
