"use client";
import { useEffect,useState } from "react";
import { Ban } from "lucide-react";
import { toast } from "sonner";
import { Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle } from "@/components/ui/dialog";
import { BrandButton } from "@/components/ui/brand-button";
import type { AppointmentDateBlock } from "@/types/appointment";
const field="h-11 w-full rounded-md border border-[#343434] bg-[#101010] px-3 text-[15px] text-white outline-none focus:border-[#e60012]";
export function BlockDateModal({open,onOpenChange,initialDate,onSaved,isDateAvailable}:{open:boolean;onOpenChange:(open:boolean)=>void;initialDate:string;onSaved:(block:AppointmentDateBlock)=>void;isDateAvailable:(date:string)=>boolean}){const [date,setDate]=useState(initialDate);const [reason,setReason]=useState("");const [saving,setSaving]=useState(false);useEffect(()=>{
// Reinicializa os campos a cada nova abertura do modal.
// eslint-disable-next-line react-hooks/set-state-in-effect
setDate(initialDate);
setReason("");
},[initialDate,open]);async function submit(event:React.FormEvent){event.preventDefault();if(!isDateAvailable(date)){toast.error("Esta data não pode ser bloqueada.");return;}setSaving(true);try{const response=await fetch("/api/appointment-blocks",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({date,reason})});const result=await response.json() as {message?:string;data?:AppointmentDateBlock};if(!response.ok||!result.data){toast.error(result.message??"Não foi possível bloquear a data.");return;}onSaved(result.data);onOpenChange(false);toast.success("Data bloqueada.");}catch{toast.error("Não foi possível bloquear a data.");}finally{setSaving(false);}}return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="border-[#353535] bg-[#151515] text-white sm:max-w-md"><DialogHeader><DialogTitle className="flex items-center gap-2"><Ban className="text-[#e60012]"/>Bloquear data</DialogTitle><DialogDescription className="text-[#999]">A data ficará indisponível para novos agendamentos.</DialogDescription></DialogHeader><form onSubmit={submit} className="mt-2 space-y-4"><label className="block"><span className="mb-2 block text-sm font-semibold text-[#ccc]">Data *</span><input required type="date" value={date} onChange={e=>setDate(e.target.value)} className={field}/></label><label className="block"><span className="mb-2 block text-sm font-semibold text-[#ccc]">Motivo *</span><input required value={reason} onChange={e=>setReason(e.target.value)} className={field} placeholder="Ex.: Oficina fechada"/></label><div className="flex justify-end gap-3"><BrandButton type="button" variant="secondary" onClick={()=>onOpenChange(false)}>Voltar</BrandButton><BrandButton disabled={saving}>{saving?"Bloqueando...":"Bloquear data"}</BrandButton></div></form></DialogContent></Dialog>}
