"use client";
import { useEffect } from "react";
import { useRouter } from "next/navigation";
type Tool={name:string;title:string;description:string;inputSchema:Record<string,unknown>;annotations:{readOnlyHint:boolean;untrustedContentHint:boolean};execute:(input:unknown)=>Promise<unknown>|unknown};
type ModelContext={registerTool:(tool:Tool,options?:{signal?:AbortSignal})=>void|Promise<void>};
declare global { interface Document { readonly modelContext?:ModelContext; } }
export function WebMcpTools(){const router=useRouter();useEffect(()=>{const context=document.modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const register=(tool:Tool)=>{try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>undefined);}catch{}}
  register({name:"search_service_orders",title:"Buscar ordens de serviço",description:"Busca o histórico da NUNA MOTO por placa, modelo ou ano.",inputSchema:{type:"object",properties:{query:{type:"string"}},required:["query"],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},async execute(input){const query=typeof input==="object"&&input!==null&&"query" in input?String((input as {query:unknown}).query):"";if(!query.trim())throw new Error("Informe uma placa, modelo ou ano.");const response=await fetch(`/api/service-orders?q=${encodeURIComponent(query)}`);if(!response.ok)throw new Error("Não foi possível buscar o histórico.");const result=await response.json() as {data?:Array<{number:string;plate:string;model:string;date:string}>};router.push(`/historico?q=${encodeURIComponent(query)}`);return {count:result.data?.length??0,orders:result.data?.slice(0,10)??[]};}});
  register({name:"start_service_order_creation",title:"Iniciar nova Ordem de Serviço",description:"Abre o formulário para registrar um novo atendimento.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(){router.push("/os/nova");return {status:"form_opened"};}});
  return()=>lifecycle.abort();},[router]);return null;}
