import { notFound } from "next/navigation";
import { Bike,CalendarClock,Gauge,MessageCircle } from "lucide-react";
import { AppShell } from "@/components/layout/app-shell";
import { PageHeader } from "@/components/ui/page-header";
import { OrderTable } from "@/components/service-orders/order-table";
import { findByPlate } from "@/lib/data/service-orders";
import { formatDateBR,formatMileage,formatWhatsapp } from "@/lib/utils/formatters";
export default async function MotorcyclePage({params}:{params:Promise<{placa:string}>}){const plate=decodeURIComponent((await params).placa).toUpperCase();const orders=await findByPlate(plate);if(!orders.length)notFound();const latest=orders[0];const previous=orders[1];const difference=previous?latest.mileage-previous.mileage:null;return <AppShell><PageHeader eyebrow="Histórico da motocicleta" title={latest.model} description={`${latest.year} · ${latest.plate}`}/><div className="mb-6 grid gap-4 lg:grid-cols-[1.4fr_1fr_1fr]"><section className="speed-stripe rounded-lg border border-[#2c2c2c] bg-[#151515] p-6"><div className="flex items-start justify-between"><div><span className="text-xs font-bold uppercase tracking-wider text-[#777]">Identificação</span><p className="mt-2 font-mono text-2xl font-black tracking-wider text-white">{latest.plate}</p><p className="mt-2 text-[#aaa]">{latest.customerName}</p><p className="mt-1 flex items-center gap-2 text-sm text-[#888]"><MessageCircle size={15}/>{formatWhatsapp(latest.whatsapp)}</p></div><Bike className="text-[#e60012]"/></div></section><VisitCard label="Último atendimento" date={latest.date} mileage={latest.mileage} icon={<CalendarClock/>}/>{previous?<VisitCard label="Atendimento anterior" date={previous.date} mileage={previous.mileage} icon={<Gauge/>}/>:<div className="rounded-lg border border-dashed border-[#333] p-5 text-sm text-[#777]">Ainda não há atendimento anterior.</div>}</div>{difference!==null&&<div className="mb-7 rounded-md border-l-2 border-[#e60012] bg-[#171717] px-5 py-4 text-sm text-[#ccc]"><strong className="text-white">{formatMileage(difference)}</strong> rodados desde o atendimento anterior.</div>}<div className="mb-4"><h2 className="text-lg font-black text-white">Ordens de Serviço</h2><p className="mt-1 text-sm text-[#888]">Mais recentes primeiro</p></div><OrderTable orders={orders}/></AppShell>}
function VisitCard({label,date,mileage,icon}:{label:string;date:string;mileage:number;icon:React.ReactNode}){return <div className="rounded-lg border border-[#2c2c2c] bg-[#151515] p-5"><div className="flex items-center justify-between text-[#e60012]"><span className="text-xs font-black uppercase tracking-wider text-[#777]">{label}</span>{icon}</div><p className="mt-4 font-bold text-white">{formatDateBR(date)}</p><p className="mt-1 text-sm text-[#999]">{formatMileage(mileage)}</p></div>}
