"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Eye,EyeOff,LockKeyhole,UserRound } from "lucide-react";
import { Logo } from "@/components/layout/logo";
import Image from "next/image";

export default function LoginPage(){const router=useRouter();const [show,setShow]=useState(false);const [loading,setLoading]=useState(false);const [error,setError]=useState("");
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);setError("");const form=new FormData(event.currentTarget);try{const response=await fetch("/api/auth/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({username:form.get("username"),password:form.get("password")})});const result=await response.json() as {success:boolean;message?:string};if(!response.ok){setError(result.message??"Não foi possível entrar.");return;}router.replace("/dashboard");router.refresh();}catch{setError("Não foi possível entrar agora. Tente novamente.");}finally{setLoading(false);}}
  return <main className="relative grid min-h-screen place-items-center overflow-hidden bg-[#070707] px-4 py-10"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_20%_20%,rgba(239,0,25,.12),transparent_30%),linear-gradient(125deg,transparent_65%,rgba(255,255,255,.025)_65%,transparent_66%)]"/><Image src="/moto-os-identidade-completa/brand/moto-os-symbol.svg" alt="" width={420} height={420} aria-hidden className="pointer-events-none absolute -bottom-24 -right-24 h-[360px] w-[360px] opacity-[.035] sm:h-[480px] sm:w-[480px]"/><div className="relative w-full max-w-[440px]"><div className="mb-7 flex justify-center"><Logo/></div><section className="speed-stripe rounded-xl border border-[#2a2a2a] bg-[#111]/95 p-6 shadow-2xl shadow-black/60 backdrop-blur sm:p-8"><div className="mb-7"><p className="mb-2 text-xs font-bold uppercase tracking-[.23em] text-[#ef0019]">Acesso à oficina</p><h1 className="text-2xl font-black text-white">Bem-vindo de volta</h1><p className="mt-2 text-[15px] text-[#999]">Entre para consultar e registrar manutenções.</p></div><form onSubmit={submit} className="space-y-5"><label className="block"><span className="mb-2 block text-sm font-semibold text-[#ccc]">Usuário</span><span className="flex items-center rounded-md border border-[#333] bg-[#0c0c0c] px-3 focus-within:border-[#ef0019]"><UserRound size={18} className="text-[#666]"/><input name="username" autoComplete="username" required className="h-12 w-full bg-transparent px-3 text-base text-white outline-none" placeholder="Seu usuário"/></span></label><label className="block"><span className="mb-2 block text-sm font-semibold text-[#ccc]">Senha</span><span className="flex items-center rounded-md border border-[#333] bg-[#0c0c0c] px-3 focus-within:border-[#ef0019]"><LockKeyhole size={18} className="text-[#666]"/><input name="password" type={show?"text":"password"} autoComplete="current-password" required className="h-12 w-full bg-transparent px-3 text-base text-white outline-none" placeholder="Sua senha"/><button type="button" aria-label={show?"Ocultar senha":"Mostrar senha"} onClick={()=>setShow(!show)} className="p-2 text-[#777] hover:text-white">{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></span></label>{error&&<p role="alert" className="rounded-md border border-red-900/70 bg-red-950/35 px-4 py-3 text-sm text-red-200">{error}</p>}<button disabled={loading} className="flex h-12 w-full items-center justify-center rounded-md bg-[#ef0019] font-black text-white transition hover:bg-[#ff1020] disabled:opacity-60">{loading?"Entrando...":"Entrar"}</button></form></section><p className="mt-5 text-center text-xs text-[#626262]">Gestão de oficina · Moto OS</p></div></main>;
}
