create extension if not exists pgcrypto;

create table if not exists public.appointments (
  id uuid primary key default gen_random_uuid(), appointment_date date not null,
  customer_name text not null, whatsapp text not null, plate text not null, model text not null,
  year integer not null check (year between 1970 and 2200), planned_service text not null,
  notes text, status text not null default 'SCHEDULED' check (status in ('SCHEDULED', 'COMPLETED', 'CANCELLED', 'NO_SHOW')),
  service_order_id bigint, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create table if not exists public.appointment_date_blocks (
  id uuid primary key default gen_random_uuid(), block_date date not null unique,
  reason text not null, created_at timestamptz not null default now()
);

create table if not exists public.service_orders (
  id bigint generated by default as identity primary key,
  customer_name text not null, whatsapp text not null, plate text not null, model text not null,
  year integer not null check (year between 1970 and 2200), mileage integer not null check (mileage > 0),
  service_date date not null, services_performed jsonb not null default '[]'::jsonb,
  replaced_parts jsonb not null default '[]'::jsonb, total_cents integer not null check (total_cents >= 0),
  notes text, appointment_id uuid references public.appointments(id) on delete set null,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

alter table public.appointments add constraint appointments_service_order_id_fkey
  foreign key (service_order_id) references public.service_orders(id) on delete set null;

create unique index if not exists appointments_one_scheduled_per_date on public.appointments (appointment_date) where status = 'SCHEDULED';
create index if not exists service_orders_plate_idx on public.service_orders (plate);
create index if not exists service_orders_date_idx on public.service_orders (service_date desc);
create index if not exists appointments_date_idx on public.appointments (appointment_date);

create or replace function public.set_updated_at() returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end;
$$;
drop trigger if exists service_orders_set_updated_at on public.service_orders;
create trigger service_orders_set_updated_at before update on public.service_orders for each row execute function public.set_updated_at();
drop trigger if exists appointments_set_updated_at on public.appointments;
create trigger appointments_set_updated_at before update on public.appointments for each row execute function public.set_updated_at();

create or replace function public.prevent_calendar_conflict() returns trigger language plpgsql as $$
begin
  if tg_table_name = 'appointments' and new.status = 'SCHEDULED' then
    if exists (select 1 from public.appointment_date_blocks where block_date = new.appointment_date) then raise exception 'DATE_UNAVAILABLE'; end if;
  elsif tg_table_name = 'appointment_date_blocks' then
    if exists (select 1 from public.appointments where appointment_date = new.block_date and status = 'SCHEDULED') then raise exception 'DATE_UNAVAILABLE'; end if;
  end if;
  return new;
end;
$$;
drop trigger if exists appointments_prevent_block_conflict on public.appointments;
create trigger appointments_prevent_block_conflict before insert or update on public.appointments for each row execute function public.prevent_calendar_conflict();
drop trigger if exists blocks_prevent_appointment_conflict on public.appointment_date_blocks;
create trigger blocks_prevent_appointment_conflict before insert or update on public.appointment_date_blocks for each row execute function public.prevent_calendar_conflict();

alter table public.service_orders enable row level security;
alter table public.appointments enable row level security;
alter table public.appointment_date_blocks enable row level security;
-- Sem políticas para anon/authenticated: somente a service role do servidor acessa os dados.
