"use client";
import { useMemo,useState } from "react";
import { useRouter } from "next/navigation";
import { AlertTriangle,CalendarCheck,Plus,Save,Trash2 } from "lucide-react";
import { toast } from "sonner";
import { MOTORCYCLE_MODELS } from "@/constants/motorcycles";
import type { ServiceOrder,ServiceOrderForm,ServiceOrderItem } from "@/types/service-order";
import { formatCurrencyBRL,formatMileage,formatWhatsapp,normalizePlate,normalizeWhatsapp,parseCurrencyToCents } from "@/lib/utils/formatters";
import { BrandButton } from "@/components/ui/brand-button";

const field="h-12 w-full rounded-md border border-[#343434] bg-[#101010] px-3 text-base text-white outline-none transition focus:border-[#e60012]";
const label="mb-2 block text-sm font-semibold text-[#c6c6c6]";
const emptyItem=():ServiceOrderItem=>({description:""});
function today(){return new Intl.DateTimeFormat("en-CA",{timeZone:"America/Sao_Paulo"}).format(new Date());}
function blank():ServiceOrderForm{return {customerName:"",whatsapp:"",plate:"",model:"",year:new Date().getFullYear(),mileage:0,date:today(),servicesPerformed:[emptyItem()],replacedParts:[],totalCents:0,notes:""};}
function sumItems(services:ServiceOrderItem[],parts:ServiceOrderItem[]){return [...services,...parts].reduce((total,item)=>total+(item.valueCents??0),0);}
function hasItemValues(services:ServiceOrderItem[],parts:ServiceOrderItem[]){return [...services,...parts].some(item=>item.valueCents!==undefined);}

export function ServiceOrderFormView({orders,current,prefill,appointmentId,appointmentReference}:{orders:ServiceOrder[];current?:ServiceOrder;prefill?:Partial<ServiceOrderForm>;appointmentId?:string;appointmentReference?:string}){
  const router=useRouter();
  const [form,setForm]=useState<ServiceOrderForm>(current?{customerName:current.customerName,whatsapp:current.whatsapp,plate:current.plate,model:current.model,year:current.year,mileage:current.mileage,date:current.date,servicesPerformed:current.servicesPerformed.map(item=>({...item})),replacedParts:current.replacedParts.map(item=>({...item})),totalCents:current.totalCents,notes:current.notes,appointmentId:current.appointmentId}:{...blank(),...prefill});
  const [saving,setSaving]=useState(false);const [known,setKnown]=useState(false);
  const previous=useMemo(()=>orders.filter(o=>o.plate===form.plate&&o.id!==current?.id).sort((a,b)=>b.date.localeCompare(a.date))[0],[orders,form.plate,current?.id]);
  const mileageWarning=previous&&form.mileage>0&&form.mileage<previous.mileage;
  const itemTotal=sumItems(form.servicesPerformed,form.replacedParts);
  const hasValues=hasItemValues(form.servicesPerformed,form.replacedParts);

  function update<K extends keyof ServiceOrderForm>(key:K,value:ServiceOrderForm[K]){setForm(old=>({...old,[key]:value}));}
  function plateChanged(value:string){const plate=normalizePlate(value);const history=orders.filter(o=>o.plate===plate).sort((a,b)=>b.date.localeCompare(a.date));setKnown(history.length>0);if(history[0]&&!current)setForm(old=>({...old,plate,customerName:history[0].customerName,whatsapp:history[0].whatsapp,model:history[0].model,year:history[0].year}));else update("plate",plate);}
  function descriptionChanged(key:"servicesPerformed"|"replacedParts",index:number,description:string){setForm(old=>({...old,[key]:old[key].map((item,i)=>i===index?{...item,description}:item)}));}
  function valueChanged(key:"servicesPerformed"|"replacedParts",index:number,raw:string){const digits=raw.replace(/\D/g,"");const valueCents=digits?Number(digits):undefined;setForm(old=>{const items=old[key].map((item,i)=>i===index?{...item,valueCents}:item);const services=key==="servicesPerformed"?items:old.servicesPerformed;const parts=key==="replacedParts"?items:old.replacedParts;return {...old,[key]:items,totalCents:sumItems(services,parts)};});}
  function arrayRemove(key:"servicesPerformed"|"replacedParts",index:number){setForm(old=>{let items=old[key].filter((_,i)=>i!==index);if(key==="servicesPerformed"&&items.length===0)items=[emptyItem()];const services=key==="servicesPerformed"?items:old.servicesPerformed;const parts=key==="replacedParts"?items:old.replacedParts;return {...old,[key]:items,totalCents:sumItems(services,parts)};});}
  function arrayAdd(key:"servicesPerformed"|"replacedParts"){setForm(old=>({...old,[key]:[...old[key],emptyItem()]}));}
  async function submit(event:React.FormEvent){event.preventDefault();setSaving(true);const payload={...form,appointmentId:appointmentId??form.appointmentId,servicesPerformed:form.servicesPerformed.filter(item=>item.description.trim()),replacedParts:form.replacedParts.filter(item=>item.description.trim()),whatsapp:normalizeWhatsapp(form.whatsapp)};try{const response=await fetch(current?`/api/service-orders/${current.id}`:"/api/service-orders",{method:current?"PUT":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const result=await response.json() as {success:boolean;message?:string;data?:ServiceOrder};if(!response.ok||!result.data){toast.error(result.message??"Não foi possível salvar a Ordem de Serviço.");return;}toast.success(current?"Ordem de Serviço atualizada com sucesso.":"Ordem de Serviço criada com sucesso.");router.push(`/os/${result.data.id}`);router.refresh();}catch{toast.error("Não foi possível salvar a Ordem de Serviço.");}finally{setSaving(false);}}

  return <form onSubmit={submit} className="space-y-6">{appointmentReference&&<div className="flex gap-3 rounded-lg border border-[#4a3234] bg-[#211315] p-4 text-sm text-[#ddd]"><CalendarCheck className="shrink-0 text-[#e60012]" size={20}/><div><strong className="text-white">Referência do agendamento</strong><p className="mt-1 leading-6 text-[#aaa]">{appointmentReference}</p><p className="mt-1 text-xs text-[#777]">Preencha abaixo somente os serviços efetivamente realizados.</p></div></div>}
    <section className="rounded-lg border border-[#292929] bg-[#141414] p-5 sm:p-6"><div className="mb-5"><h2 className="font-black text-white">Cliente e motocicleta</h2><p className="mt-1 text-sm text-[#888]">A placa identifica a moto e recupera seu último cadastro.</p></div><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4"><label><span className={label}>Placa *</span><input required value={form.plate} onChange={e=>plateChanged(e.target.value)} placeholder="ABC1D23" className={`${field} font-mono uppercase tracking-wider`}/>{known&&<span className="mt-2 block text-xs font-semibold text-[#e1b84f]">Histórico encontrado · dados preenchidos</span>}</label><label className="xl:col-span-2"><span className={label}>Nome do cliente *</span><input required value={form.customerName} onChange={e=>update("customerName",e.target.value)} className={field}/></label><label><span className={label}>WhatsApp *</span><input required value={formatWhatsapp(form.whatsapp)} onChange={e=>update("whatsapp",normalizeWhatsapp(e.target.value))} inputMode="tel" placeholder="(81) 99999-9999" className={field}/></label><label className="md:col-span-2"><span className={label}>Modelo da moto *</span><select required value={form.model} onChange={e=>update("model",e.target.value)} className={field}><option value="">Selecione o modelo</option>{Object.entries(MOTORCYCLE_MODELS).map(([category,models])=><optgroup key={category} label={category}>{models.map(model=><option key={model}>{model}</option>)}</optgroup>)}</select></label><label><span className={label}>Ano *</span><input required type="number" min="1970" max={new Date().getFullYear()+1} value={form.year} onChange={e=>update("year",Number(e.target.value))} className={field}/></label><label><span className={label}>Data *</span><input required type="date" value={form.date} onChange={e=>update("date",e.target.value)} className={field}/></label></div></section>
    <section className="rounded-lg border border-[#292929] bg-[#141414] p-5 sm:p-6"><h2 className="mb-5 font-black text-white">Atendimento</h2><label className="block max-w-md"><span className={label}>Quilometragem *</span><input required type="number" min="1" step="1" value={form.mileage||""} onChange={e=>update("mileage",Number(e.target.value))} placeholder="18.540 km" className={field}/></label>{mileageWarning&&<div className="mt-4 flex gap-3 rounded-md border border-amber-800/50 bg-amber-950/20 p-4 text-sm text-amber-200"><AlertTriangle className="shrink-0" size={19}/><p>A quilometragem informada é menor que a última registrada para esta moto: <strong>{formatMileage(previous.mileage)}</strong>. Você ainda pode continuar.</p></div>}
      <DynamicList title="Serviços realizados *" itemName="serviço" values={form.servicesPerformed} onDescriptionChange={(i,v)=>descriptionChanged("servicesPerformed",i,v)} onValueChange={(i,v)=>valueChanged("servicesPerformed",i,v)} onRemove={i=>arrayRemove("servicesPerformed",i)} onAdd={()=>arrayAdd("servicesPerformed")} addText="Adicionar serviço" requiredFirst/>
      <DynamicList title="Peças substituídas" itemName="peça" values={form.replacedParts} onDescriptionChange={(i,v)=>descriptionChanged("replacedParts",i,v)} onValueChange={(i,v)=>valueChanged("replacedParts",i,v)} onRemove={i=>arrayRemove("replacedParts",i)} onAdd={()=>arrayAdd("replacedParts")} addText="Adicionar peça"/>
      <div className="mt-7 grid gap-4 border-t border-[#2b2b2b] pt-6 md:grid-cols-[1fr_280px] md:items-end"><div><p className="text-sm font-bold text-white">{hasValues?`Soma dos itens: ${formatCurrencyBRL(itemTotal)}`:"Nenhum valor individual informado"}</p><p className="mt-1 text-sm leading-5 text-[#888]">{hasValues?"O total foi atualizado automaticamente. Você pode ajustá-lo manualmente, se necessário.":"Preencha o valor final manualmente ou informe valores nos itens acima."}</p></div><label><span className={label}>Valor Total da OS *</span><input required value={formatCurrencyBRL(form.totalCents)} onChange={e=>update("totalCents",parseCurrencyToCents(e.target.value))} inputMode="numeric" className={`${field} text-lg font-black`}/></label></div>
    </section>
    <section className="rounded-lg border border-[#292929] bg-[#141414] p-5 sm:p-6"><label><span className={label}>Observações</span><textarea value={form.notes??""} onChange={e=>update("notes",e.target.value)} rows={4} className="w-full resize-y rounded-md border border-[#343434] bg-[#101010] p-3 text-base text-white outline-none focus:border-[#e60012]" placeholder="Informações adicionais sobre o atendimento"/></label></section>
    <div className="flex flex-col-reverse justify-end gap-3 sm:flex-row"><BrandButton type="button" variant="secondary" onClick={()=>router.back()}>Cancelar</BrandButton><BrandButton disabled={saving}><Save size={18}/>{saving?"Salvando...":current?"Salvar alterações":"Criar Ordem de Serviço"}</BrandButton></div>
  </form>;
}

function DynamicList({title,itemName,values,onDescriptionChange,onValueChange,onRemove,onAdd,addText,requiredFirst=false}:{title:string;itemName:string;values:ServiceOrderItem[];onDescriptionChange:(i:number,v:string)=>void;onValueChange:(i:number,v:string)=>void;onRemove:(i:number)=>void;onAdd:()=>void;addText:string;requiredFirst?:boolean}){return <div className="mt-7"><div className="mb-3 flex items-end justify-between gap-3"><span className="text-sm font-semibold text-[#c6c6c6]">{title}</span><span className="text-xs text-[#777]">Valores opcionais</span></div><div className="space-y-3">{values.map((item,index)=><div key={index} className="grid gap-2 sm:grid-cols-[minmax(0,1fr)_180px_48px]"><label><span className="sr-only">Descrição do {itemName} {index+1}</span><input required={requiredFirst&&index===0} value={item.description} onChange={e=>onDescriptionChange(index,e.target.value)} className={field} placeholder={itemName==="serviço"?"Ex.: Troca de óleo":"Ex.: Filtro de óleo"}/></label><label><span className="sr-only">Valor do {itemName} {index+1}</span><input value={item.valueCents===undefined?"":formatCurrencyBRL(item.valueCents)} onChange={e=>onValueChange(index,e.target.value)} inputMode="numeric" className={field} placeholder="Valor opcional"/></label><button type="button" aria-label={`Excluir ${itemName}`} onClick={()=>onRemove(index)} className="grid h-12 w-full place-items-center rounded-md border border-[#3b2b2c] text-[#c66] hover:bg-red-950/30 hover:text-red-400 sm:w-12"><Trash2 size={18}/></button></div>)}</div><button type="button" onClick={onAdd} className="mt-3 inline-flex min-h-10 items-center gap-2 rounded-md border border-[#343434] px-3 text-sm font-bold text-[#ccc] hover:bg-[#1e1e1e] hover:text-white"><Plus size={17}/>{addText}</button></div>}
